### PR TITLE
Fix invalid headers in gcridge_map.fits and hessj1825_map.fits

### PR DESCRIPTION
**Pull request by QRemy**
This PR fix invalid FITS headers for two models :
gcridge_map.fits : units Degrees->deg
hessj1825_map.fits : missing extension reference removed

### CODE REVIEW

**Comment by tibaldo** [comment]
The files in skymodel/output must not be modified. They are automatically generated. If they present any issues the parent files/scripts should be modified instead.
1) gcridge_map.fits: the parent file to be modified in case would be skymodel/iem/gcridge_map.fits. However, this file is merely a copy of the template distributed by the H.E.S.S. collaboration (https://www.mpi-hd.mpg.de/hfm/HESS/pages/publications/auxiliary/gcdiffuse_auxinfo.html), and standard FITS reading tools (fv, ds9), as well as GammaLib can correctly read the header keywords. Could you please point out the piece of the official FITS standard documentation that does not contemplate or deprecate the use of 'degrees'?
2) hessj1825_map.fits: could you please fix the parent script skymodel/known_sources/templates/HESS_J1825_map_creator.py? Again, no problem seen with standard FITS readers, could you please detail what the actual problem is?
3) Why did you delete the file skymodel/known-sources/templates/hess_j1800-240c.xml?

**Comment by QRemy** [comment]
1. The header unit is 'Degrees' so it's likely a problem of case-sensitive reading, here is a related issue:
https://github.com/astropy/astropy/issues/2977, it was closed considering that the problem comes from the FITS file.
2. The keyword BANDSHDU= 'PRIMARY_BANDS' seems to refer to a missing extension so I removed it
3. When I cloned the repo the file was already marked as removed while still there, I didn't manage to unstage that change, no idea why.

**Comment by tibaldo** [comment]
Ok. for 1 and 2 could you please fix your modifications changing the input file/script rather than the output ones?
For 3: this is a mistake, not sure what the origin is, but that file is needed, we cannot remove it.

**Comment by QRemy** [comment]
Ok modified

**Comment by tibaldo** [comment]
Great, thanks a lot

**Pull request merged**
