### PR TITLE
Add SN1006 template

### PR DESCRIPTION
**Pull request by Antonio-Tutone**
addition of map and model for SN1006

### CODE REVIEW

**Comment by tibaldo** [comment]
Ciao @Antonio-Tutone , thanks for adding the template for SN 1006!
I don't recall any discussion on this source. Could you please specify what are the data sources/references for the model you propose to use. Possibly they should be included as comments in the XML for future reference.

**Comment by Antonio-Tutone** [comment]
Hi @tibaldo ! I've added the comments as you suggested. Hope to have done it properly

**Comment by tibaldo** [comment]
Thanks for the reference @Antonio-Tutone !
A few comments on the XML for your consideration:
- the spectral indices appear to be positive, which is probably a mistake; for photon fluxes decreasing with energy the spectral indices should be negative, see http://cta.irap.omp.eu/ctools/users/user_manual/models_spectral.html
- also the values of the prefactors are weird, for a 10% Crab I would expect a prefactor of the order of 10-11/10-13 in the units required by ctools; have you verified that you obtain the correct fluxes in ctools? Is this due to a normalization of the spatial templates different from 1? (for easier use I'd recommend to normalize the spatial template to 1 and set the normalization only through the spectral part)

**Comment by Antonio-Tutone** [comment]
thanks again for your help @tibaldo !
I changed the spectral index sign and therefore recalculated the prefactor. Now the value it's physically correct.
Warning! Ctools use units of photons cm−2 s−1 MeV−1 so we should expect a prefactor of the order of 10^-17/10^-19 for a 10% Crab.
The 10^-11/10^-13 is expected for units of cm−2 s−1 TeV−1.
However, to verify this "units" problem, I'm going to simulate the source and calculate the flux with ctools to compare the result with my own calculations (which give back the same results of Acero 2010 for the flux)

**Comment by tibaldo** [comment]
Thanks again @Antonio-Tutone , I think the prefactor is correct as you say, sorry for the confusion (I also tend to think in TeV rather than MeV as ctools do). I'll wait for the results of the simulation anyway, please confirm when you are ready to merge.
Small comment: the error cannot be negative, and anyway you can drop the errors for the parameters completely for a model to be used in input for a simulation.

**Comment by Antonio-Tutone** [comment]
Thanks @tibaldo ! 
The fluxes obtained from this model are consistent with those reported in Acero et al. 2010.
Now the model can be merged.

**Pull request merged**
